// List<String> districts = [
//   'Thiruvananthapuram',
//   'Kollam',
//   'Pathanamthitta',
//   'Alappuzha',
//   'Kottayam',
//   'Idukki',
//   'Ernakulam',
//   'Thrissur',
//   'Palakkad',
//   'Malappuram',
//   'Kozhikode',
//   'Wayanad',
//   'Kannur',
//   'Kasaragod',
// ];
List<String> block = [
  "Athiyanoor",
  "Chiyrayinkeezhu",
  "Pothencode",
  "Kilimanoor",
  "Nedumangad",
  "Nemom",
  "Parassala",
  "Perumkadavila",
  "Vamanapuram",
  "Varkala",
  "Vellanad",
  "",
  "Anchal",
  "Chadaya mangalam",
  "Chavara",
  "Chittumala",
  "Ithikkara",
  "Kottarakkara",
  "Mughathala",
  "Oachira",
  "Pathanapuram",
  "Sasthamkotta",
  "Vettikavala",
  "",
  "Mallappally",
  "Pulikeezhu",
  "Koipuram",
  "Elanthoor",
  "Ranni",
  "Konni",
  "Pandalam",
  "Parakode",
  "",
  "Ambalapuzha",
  "Aryad",
  "Bharanicavu",
  "Champakulam",
  "Chengannur",
  "Haripad",
  "Kanjikuzhy",
  "Mavelikara",
  "Muthukulam",
  "Pattanakkad",
  "Thycattussery",
  "Veliyanad",
  "",
  "Erattupetta",
  "Ettumannoor",
  "Kaduthuruthy",
  "Kanjirappally",
  "Lalam",
  "Madappally",
  "Pallom",
  "Pampady",
  "Uzhavoor",
  "Vazhoor",
  "Vaikom",
  "",
  "Adimaly",
  "Azhutha",
  "Devikulam",
  "Elamdesam",
  "Idukki",
  "Kattappana",
  "Nedumkandam",
  "Thodupuzha",
  "",
  "Alangad",
  "Angamaly",
  "Edappally",
  "Koovappady",
  "Kothamangalam",
  "Mulanthuruthy",
  "Moovattupuzha",
  "Palluruthy",
  "Pampakuda",
  "North Paravoor",
  "Parakadavu",
  "Vadavucode",
  "Vazhakulam",
  "Vypin",
  "",
  "Anthikkad",
  "Chalakudy",
  "Chavakkad",
  "Cherpu",
  "Chowannur",
  "Irinjalakuda",
  "Kodakara",
  "Mala",
  "Mathilakam",
  "Mullassery",
  "Ollukkara",
  "Pazhayannur",
  "Puzhakkal",
  "Thalikulam",
  "Vellangallur",
  "Wadakkanchery",
  "",
  "Alathur",
  "Attappady (ITDP)",
  "Chittur",
  "Kollengode",
  "Kuzhalmannam",
  "Malampuzha",
  "Mannarkad",
  "Nenmara",
  "Ottappalam",
  "Palakkad",
  "Pattambi",
  "Sreekrishna puram",
  "Thrithala",
  "",
  "Areakode",
  "Kondotty",
  "Kuttippuram",
  "Malappuram",
  "Mankada",
  "Nilambur",
  "Perinthalmanna",
  "Perumpadappu",
  "Ponnani",
  "Thanur",
  "Tirur",
  "Thirurangadi",
  "Vengara",
  "Wandoor",
  "Kalikavu",
  "",
  "Balussery",
  "Chelannur",
  "Koduvally",
  "Kozhikode",
  "Kunnamangalam",
  "Kunnummal",
  "Meladi",
  "Panthalayani",
  "Perambra",
  "Thodannur",
  "Tuneri",
  "Vatakara",
  "",
  "Kalpetta",
  "Sulthan Bathery",
  "Mananthavady",
  "Panamaram",
  "",
  "Kannur",
  "Taliparamba",
  "Payyannur",
  "Edakkad",
  "Thalassery",
  "Kuthuparamba",
  "Iritty",
  "Irikkur",
  "Peravoor",
  "Panoor",
  "Kalliassery",
  "",
  "Manjeswaram",
  "Kasaragod",
  "Kanhangad",
  "Nileshwaram",
  "Karaduka",
  "Parappa",

];
List<String> panchayth = [
  // ["Chemmaruthy",
  // "Edava",
  // "Elakamon",
  // "Manamboor",
  // "Ottoor",
  // "Cherunniyoor",
  // "Vettoor",],
  // ["Kilimanoor",
  // "Pazhayakunnumel",
  // "Karavaram",
  // "Madavoor",
  // "Pallickal",
  // "Nagaroor",
  // "Navaikulam",
  // "Pulimath",]
  // "Anchuthengu",
  "Vakkom",
  "Chirayinkeezhu",
  "Kizhuvilam",
  "Mudakkal",
  "Kadakkavoor",
  "Kallara",
  "Nellanad",
  "Pullampara",
  "Vamanapuram",
  "Pangode",
  "Nanniyode",
  "Peringammala",
  "Manickal",
  "Aryanad",
  "Poovachal",
  "Vellanad",
  "Vithura",
  "Uzhamalakkal",
  "Kuttichal",
  "Tholicode",
  "Kattakada",
  "Anad",
  "Aruvikkara",
  "Panavoor",
  "Karakulam",
  "Vembayam",
  "Andoorkonam",
  "Kadinamkulam",
  "Mangalapuram",
  "Pothencode",
  "Azhoor",
  "Balaramapuram",
  "Pallichal",
  "Maranalloor",
  "Malayinkeezh",
  "Vilappil",
  "Vilavoorkal",
  "Kalliyoor",
  "Perumkadavila",
  "Kollayil",
  "Ottasekharamangalam",
  "Aryancode",
  "Kallikkadu",
  "Kunnathukal",
  "Vellarada",
  "Amboori",
  "Athiyannoor",
  "Kanjiramkulam",
  "Karumkulam",
  "Kottukal",
  "Venganoor",
  "Chenkal",
  "Karode",
  "Kulathoor",
  "Parassala",
  "Thirupuram",
  "Poovar",
  "Oachira",
  "Kulasekharapuram",
  "Clappana",
  "Thazhava",
  "Alappad",
  "Thodiyoor",
  "Sasthamcotta",
  "West Kallada",
  "Sooranad South",
  "Poruvazhy",
  "Kunnathoor",
  "Sooranad North",
  "Mynagappally",
  "Ummannoor",
  "Vettikavala",
  "Melila",
  "Mylom",
  "Kulakkada",
  "Pavithreswaram",
  "Vilakkudy",
  "Thalavoor",
  "Piravanthoor",
  "Pattazhi Vadakkekara",
  "Pattazhi",
  "Pathanapuram",
  "Kulathupuzha",
  "Yeroor",
  "Alayamon",
  "Anchal",
  "Edamulackal",
  "Karavaloor",
  "Thenmala",
  "Aryankavu",
  "Veliyam",
  "Pooyappally",
  "Kareepra",
  "Ezhukone",
  "Neduvathoor",
  "Perinad",
  "Kundara",
  "East Kallada",
  "Perayam",
  "Munroethuruth",
  "Panayam",
  "Thrikkaruva",
  "Thekkumbhagom",
  "Chavara",
  "Thevalakkara",
  "Panmana",
  "Neendakara",
  "Mayyanad",
  "Thrikkovilvattom",
  "Kottamkara",
  "Elampalloor",
  "Nedumpana",
  "Poothakulam",
  "Kalluvathukkal",
  "Chathannoor",
  "Adichanalloor",
  "Chirakkara",
  "Chithara",
  "Kadakkal",
  "Chadayamangalam",
  "Ittiva",
  "Velinalloor",
  "Elamadu",
  "Nilamel",
  "Kummil",
  "Anicadu",
  "Kaviyoor",
  "Kottanad",
  "Kottangal",
  "Kallooppara",
  "Kunnamthanam",
  "Mallappally",
  "Kadapra",
  "Kuttoor",
  "Niranam",
  "Nedumpuram",
  "Peringara",
  "Ayroor",
  "Eraviperoor",
  "Koipuram",
  "Thottappuzhassery",
  "Ezhumattoor",
  "Puramattom",
  "Omalloor",
  "Chenneerkara",
  "Elanthoor",
  "Cherukole",
  "Kozhencherry",
  "Mallappuzhassery",
  "Naranganam",
  "Ranni Pazhavangadi",
  "Ranni",
  "Ranni Angadi",
  "Ranni Perunadu",
  "Vadaserikara",
  "Chittar",
  "Seethathodu",
  "Naranammoozhy",
  "Vechoochira",
  "Konni",
  "Aruvappulam",
  "Pramadom",
  "Mylapra",
  "Vallicode",
  "Thannithodu",
  "Malayalapuzha",
  "Pandalam Thekkekara",
  "Thumpamon",
  "Aranmula",
  "Mezhuveli",
  "Kulanada",
  "Enadimangalam",
  "Erathu",
  "Ezhamkulam",
  "Kadampanad",
  "Kalanjoor",
  "Kodumon",
  "Pallickal",
  "Arookutty",
  "Chennam Pallippuram",
  "Panavally",
  "Perumpalam",
  "Thycattussery",
  "Vayalar",
  "Pattanakkad",
  "Thuravoor",
  "Kuthiathod",
  "Kodamthuruth",
  "Ezhupunna",
  "Aroor",
  "Mararikulam North",
  "Kanjikuzhy",
  "Thanneermukkom",
  "Cherthala South",
  "Kadakkarappally",
  "Aryad",
  "Mannancherry",
  "Mararikulam South",
  "Muhamma",
  "Purakkad",
  "Ambalappuzha South",
  "Ambalappuzha North",
  "Punnapra South",
  "Punnapra North",
  "Thalavady",
  "Edathua",
  "Thakazhy",
  "Nedumudi",
  "Champakulam",
  "Kainakary",
  "Muttar",
  "Veliyanad",
  "Neelamperoor",
  "Kavalam",
  "Pulincunnoo",
  "Ramankary",
  "Mulakuzha",
  "Venmoney",
  "Cheriyanad",
  "Ala",
  "Puliyoor",
  "Budhanoor",
  "Pandanad",
  "Thiruvanvandoor",
  "Karthikappally",
  "Thrikkunnappuzha",
  "Kumarapuram",
  "Karuvatta",
  "Pallippad",
  "Cheruthana",
  "Veeyapuram",
  "Mavelikara Thekkekara",
  "Chettikulangara",
  "Chennithala-Thripperumthura",
  "Thazhakara",
  "Mannar",
  "Nooranad",
  "Vallikunnam",
  "Bharanickavu",
  "Mavelikara Thamarakulam",
  "Chunakara",
  "Palamel",
  "Pathiyoor",
  "Kandalloor",
  "Cheppad",
  "Muthukulam",
  "Arattupuzha",
  "Krishnapuram",
  "Devikulangara",
  "Chingoli",
  "Thalayazham",
  "Chempu",
  "Maravanthuruthu",
  "TV Puram",
  "Vechoor",
  "Udayanapuram",
  "Kaduthuruthy",
  "Kallara",
  "Mulakulam",
  "Neezhoor",
  "Thalayolaparambu",
  "Velloor",
  "Aymanam",
  "Athirampuzha",
  "Arpookara",
  "Neendoor",
  "Kumarakam",
  "Thiruvarppu",
  "Kadaplamattom",
  "Marangattupilly",
  "Kanakkary",
  "Veliyannoor",
  "Kuravilangad",
  "Uzhavoor",
  "Ramapuram",
  "Manjoor",
  "Bharananganam",
  "Karoor",
  "Kozhuvanal",
  "Kadanad",
  "Meenachil",
  "Mutholy",
  "Melukavu",
  "Moonnilavu",
  "Poonjar",
  "Poonjar Thekkekara",
  "Thalappalam",
  "Teekoy",
  "Thalanad",
  "Thidanad",
  "Akalakunnam",
  "Elikulam",
  "Kooroppada",
  "Pampady",
  "Pallikkathode",
  "Meenadom",
  "Kidangoor",
  "Manarcad",
  "Ayarkunnam",
  "Puthuppally",
  "Panachikkad",
  "Vijayapuram",
  "Kurichy",
  "Madappally",
  "Paippad",
  "Thrickodithanam",
  "Vakathanam",
  "Vazhappally",
  "Chirakkadavu",
  "Kangazha",
  "Nedumkunnam",
  "Vellavoor",
  "Vazhoor",
  "Karukachal",
  "Erumeli",
  "Kanjirappally",
  "Koottickal",
  "Manimala",
  "Mundakayam",
  "Parathodu",
  "Koruthodu",
  "Adimaly",
  "Konnathady",
  "Bisonvalley",
  "Vellathooval",
  "Pallivasal",
  "Marayoor",
  "Munnar",
  "Kanthalloor",
  "Vattavada",
  "Santhanpara",
  "Chinnakanal",
  "Mankulam",
  "Devikulam",
  "Edamalakudi",
  "Pampadumpara",
  "Senapathy",
  "Karunapuram",
  "Rajakkad",
  "Nedumkandam",
  "Udumbanchola",
  "Rajakumary",
  "Vannappuram",
  "Udumbanoor",
  "Kodikulam",
  "Alakode",
  "Velliyamattom",
  "Karimannoor",
  "Kudayathoor",
  "Idukki Kanjikuzhy",
  "Vathikudy",
  "Arakulam",
  "Kamakshy",
  "Vazhathope",
  "Mariyapuram",
  "Upputhara",
  "Vandanmedu",
  "Kanchiyar",
  "Erattayar",
  "Ayyappan Coil",
  "Chakkupallam",
  "Muttom",
  "Kumaramangalam",
  "Edavetty",
  "Karimkunnam",
  "Manakkad",
  "Purapuzha",
  "Peruvanthanam",
  "Kumily",
  "Kokkayar",
  "Peermade",
  "Elappara",
  "Vandiperiyar",
  "Chendamangalam",
  "Kottuvally",
  "Ezhikkara",
  "Vadakkekkara",
  "Chittattukara",
  "Karumallur",
  "Varapuzha",
  "Alangad",
  "Kadungalloor",
  "Mookkannur",
  "Thuravoor",
  "Manjapra",
  "Karukutty",
  "Ayyampuzha",
  "Kanjoor",
  "Kalady",
  "Malayattoor Neeleeswaram",
  "Asamannoor",
  "Mudakuzha",
  "Vengoor",
  "Rayamangalam",
  "Koovappady",
  "Okkal",
  "Vengola",
  "Vazhakulam",
  "Kizhakkambalam",
  "Choornikkara",
  "Edathala",
  "Keezhmad",
  "Kadamakudy",
  "Cheranalloor",
  "Mulavukad",
  "Elankunnapuzha",
  "Narakal",
  "Nayarambalam",
  "Edavanakkad",
  "Pallippuram",
  "Kuzhuppilly",
  "Chellanam",
  "Kumbalanghi",
  "Kumbalam",
  "Udayamperoor",
  "Mulanthuruthy",
  "Chottanikkara",
  "Edakkattuvayal",
  "Amballoor",
  "Maneed",
  "Poothrikka",
  "Thiruvaniyoor",
  "Vadavucode Puthencruz",
  "Mazhuvannoor",
  "Aikaranad",
  "Kunnathunad",
  "Paingottoor",
  "Nellikuzhi",
  "Pindimana",
  "Kottappady",
  "Kavalangad",
  "Varappetty",
  "Keerampara",
  "Pothanicad",
  "Pallarimangalam",
  "Kuttampuzha",
  "Elanji",
  "Thirumarady",
  "Palakuzha",
  "Pampakuda",
  "Ramamangalam",
  "Puthenvelikkara",
  "Chengamanad",
  "Nedumbassery",
  "Parakkadavu",
  "Kunnukara",
  "Sreemoolanagaram",
  "Avoly",
  "Arakuzha",
  "Valakom",
  "Paipra",
  "Kalloorkad",
  "Ayavana",
  "Manjalloor",
  "Marady",
  "Kadappuram",
  "Orumanayur",
  "Punnayur",
  "Punnayurkulam",
  "Vadakkekkad",
  "Choondal",
  "Chowannur",
  "Kadavallur",
  "Kandanassery",
  "Kattakampal",
  "Porkulam",
  "Kadangode",
  "Velur",
  "Desamangalam",
  "Erumapetty",
  "Mullurkara",
  "Thekkumkara",
  "Varavoor",
  "Chelakkara",
  "Vallathol Nagar",
  "Kondazhy",
  "Panjal",
  "Pazhayannur",
  "Thiruvilwamala",
  "Madakkathara",
  "Nadathara",
  "Pananchery",
  "Puthur",
  "Adat",
  "Avanur",
  "Kaiparambu",
  "Mulakunnathukavu",
  "Tholur",
  "Kolazhy",
  "Elavally",
  "Mullassery",
  "Pavaratty",
  "Venkitangu",
  "Engandiyur",
  "Vatanappally",
  "Thalikulam",
  "Nattika",
  "Valapad",
  "Anthikad",
  "Thanniyam",
  "Chazhur",
  "Manalur",
  "Arimpur",
  "Avinissery",
  "Cherpu",
  "Paralam",
  "Vallachira",
  "Alagappanagar",
  "Kodakara",
  "Mattathur",
  "Nenmanikkara",
  "Pudukad",
  "Thrikkur",
  "Varandarappilly",
  "Karalam",
  "Kattoor",
  "Muriyad",
  "Parappukkara",
  "Padiyur",
  "Poomangalam",
  "Puthenchira",
  "Vellangallur",
  "Velukara",
  "Edathiruthy",
  "Kaipamangalam",
  "Mathilakam",
  "Perinjanam",
  "Sreenarayanapuram",
  "Edavilangu",
  "Eriyad",
  "Aloor",
  "Annamanada",
  "Kuzhur",
  "Mala",
  "Poyya",
  "Kadukutty",
  "Kodassery",
  "Koratty",
  "Meloor",
  "Pariyaram",
  "Athirappilly",
  "Anakkara",
  "Chalissery",
  "Kappur",
  "Nagalassery",
  "Pattithara",
  "Thirumittacode",
  "Trithala",
  "Koppam",
  "Kulukkallur",
  "Muthuthala",
  "Ongallur",
  "Paruthur",
  "Thiruvegappura",
  "Vilayur",
  "Ambalappara",
  "Ananganadi",
  "Chalavara",
  "Lakkidi - Perur",
  "Vaniamkulam",
  "Trikkaderi",
  "Vallapuzha",
  "Nellaya",
  "Kadampazhipuram",
  "Karimpuzha",
  "Pookkottukavu",
  "Sreekrishnapuram",
  "Vellinezhi",
  "Karakurussi",
  "Alanallur",
  "Karimba",
  "Kottopadam",
  "Kumaramputhur",
  "Kanhirapuzha",
  "Thachanattukara",
  "Tachampara",
  "Thenkara",
  "Agali",
  "Pudur",
  "Sholayoor",
  "Keralassery",
  "Kongad",
  "Mankara",
  "Mannur",
  "Mundur",
  "Parali",
  "Pirayiri",
  "Kottayi",
  "Kuthanur",
  "Kuzhalmannam",
  "Mathur",
  "Peringottukurissi",
  "Thenkurissi",
  "Kannadi",
  "Eruthenpathy",
  "Kozhinjampara",
  "Nallepilly",
  "Perumatty",
  "Vadakarapathy",
  "Elappully",
  "Polpully",
  "Kollengode",
  "Koduvayur",
  "Muthalamada",
  "Pudunagaram",
  "Vadavannur",
  "Pattanchery",
  "Peruvemba",
  "Ayalur",
  "Nelliyampathy",
  "Elavancherry",
  "Pallassana",
  "Melarcode",
  "Nemmara",
  "Vandazhy",
  "Alathur",
  "Erimayur",
  "Kavassery",
  "Kizhakkencherry",
  "Puducode",
  "Tarur",
  "Vadakkenchery",
  "Kannambra",
  "Akathethara",
  "Malampuzha",
  "Marutharode",
  "Puduppariyaram",
  "Pudusseri",
  "Kodumbu",
  "Chaliyar",
  "Chungathara",
  "Moothedam",
  "Vazhikkadavu",
  "Edakkara",
  "Pothukallu",
  "Amarambalam",
  "Karulai",
  "Kalikavu",
  "Chokkad",
  "Karuvarakundu",
  "Tuvvur",
  "Edappatta",
  "Mampad",
  "Pandikkad",
  "Porur",
  "Thrikkalangodu",
  "Thiruvali",
  "Wandoor",
  "Chelembra",
  "Cherukavu",
  "Pallikkal",
  "Vazhayur",
  "Vazhakkad",
  "Pulikkal",
  "Muthuvalloor",
  "Urangattiri",
  "Kavanur",
  "Keezhuparamba",
  "Pulpatta",
  "Cheacode",
  "Kuzhimanna",
  "Areacode",
  "Edavanna",
  "Anakkayam",
  "Morayur",
  "Ponmala",
  "Pookkottur",
  "Kodur",
  "Othukkungal",
  "Aliparamba",
  "Elamkulam",
  "Melattur",
  "Keezhattur",
  "Thazhekkode",
  "Vettathur",
  "Pulamanthole",
  "Angadippuram",
  "Kuruva",
  "Mankada",
  "Makkaraparamba",
  "Moorkkanad",
  "Koottilangadi",
  "Puzhakkattiri",
  "Athavanad",
  "Edayur",
  "Irimbiliyam",
  "Marakkara",
  "Kuttipuram",
  "Kalpakanchery",
  "Abdurahiman Nagar",
  "Edarikode",
  "Parappur",
  "Thennala",
  "Vengara",
  "Kannamangalam",
  "Oorakam",
  "Thenhipalam",
  "Vallikkunnu",
  "Moonniyur",
  "Nannambra",
  "Peruvalloor",
  "Cheriyamundam",
  "Ozhur",
  "Tanalur",
  "Valavannur",
  "Ponmundam",
  "Niramaruthur",
  "Perumanna Klari",
  "Purathur",
  "Thalakkad",
  "Triprangode",
  "Vettom",
  "Thirunavaya",
  "Mangalam",
  "Tavanur",
  "Vattamkulam",
  "Edapal",
  "Kaladi",
  "Alamkode",
  "Maranchery",
  "Nannammukku",
  "Perumpadappa",
  "Veliancode",
  "Azhiyur",
  "Chorode",
  "Eramala",
  "Onchiyam",
  "Chekkiad",
  "Edacheri",
  "Purameri",
  "Tuneri",
  "Valayam",
  "Vanimal",
  "Nadapuram",
  "Kunnummal",
  "Kayakkody",
  "Kavilumpara",
  "Kuttiadi",
  "Maruthonkara",
  "Velom",
  "Narippatta",
  "Ayancheri",
  "Villiappally",
  "Maniyur",
  "Thiruvallur",
  "Thurayur",
  "Keezhariyur",
  "Thikkodi",
  "Meppayur",
  "Cheruvannur",
  "Nochad",
  "Changaroth",
  "Kayanna",
  "Koothali",
  "Perambra",
  "Chakkittapara",
  "Balussery",
  "Naduvannur",
  "Ulliyeri",
  "Kottur",
  "Unnikulum",
  "Panangad",
  "Koorachundu",
  "Chemanchery",
  "Arikkulam",
  "Moodadi",
  "Chengottukavu",
  "Atholi",
  "Kakkodi",
  "Chelannur",
  "Kakkur",
  "Nanminda",
  "Narikunni",
  "Thalakulathur",
  "Thiruvambadi",
  "Koodaranhi",
  "Kizhakkoth",
  "Madavoor",
  "Puduppady",
  "Thamarassery",
  "Omassery",
  "Kattippara",
  "Kodanchery",
  "Kodiyathur",
  "Kuruvattoor",
  "Mavoor",
  "Karassery",
  "Kunnamangalam",
  "Chathamangalam",
  "Peruvayal",
  "Perumanna",
  "Kadalundi",
  "Olavanna",
  "Vellamunda",
  "Thirunelly",
  "Thondernad",
  "Edavaka",
  "Thavinhal",
  "Panamaram",
  "Poothadi",
  "Mullankolly",
  "Pulpally",
  "Kaniyambetta",
  "Meenangadi",
  "Nenmeni",
  "Ambalavayal",
  "Noolpuzha",
  "Kottathara",
  "Vengappally",
  "Vythiri",
  "Muttil",
  "Pozhuthana",
  "Thariode",
  "Padinharathara",
  "Meppadi",
  "Muppainad",
  "Kunhimangalam",
  "Ramanthali",
  "Karivellur Peralam",
  "Kankol - Alappadamba",
  "Eramam Kuttur",
  "Peringome Vayakkara",
  "Cherupuzha",
  "Cheruthazham",
  "Ezhome",
  "Madayi",
  "Mattool",
  "Cherukunnu",
  "Kalliasseri",
  "Kannapuram",
  "Narath",
  "Pattuvam",
  "Chengalayi",
  "Kurumathur",
  "Pariyaram",
  "Chapparapadava",
  "Naduvil",
  "Udayagiri",
  "Alakode",
  "Kadannappally Panapuzha",
  "Eruvessy",
  "Irikkur",
  "Malappattam",
  "Payyavoor",
  "Kuttiattoor",
  "Mayyil",
  "Padiyoor",
  "Ulikkal",
  "Chirakkal",
  "Valapattanam",
  "Azhikode",
  "Pappinisseri",
  "Kadambur",
  "Chembilode",
  "Munderi",
  "Peralassery",
  "Kolachery",
  "Dharmadam",
  "Eranholi",
  "Pinarayi",
  "New Mahe",
  "Muzhappilangad",
  "Anjarakandy",
  "Vengad",
  "Kadirur",
  "Chokli",
  "Mokeri",
  "Panniyannur",
  "Triprangottoor",
  "Chittariparamba",
  "Kunnothuparamba",
  "Mangattidam",
  "Pattiam",
  "Kottayam",
  "Aralam",
  "Ayyankunnu",
  "Keezhallur",
  "Thillankery",
  "Koodali",
  "Payam",
  "Kanichar",
  "Kelakam",
  "Kottiyoor",
  "Muzhakkunnu",
  "Kolayad",
  "Malur",
  "Peravoor",
  "Mangalpady",
  "Vorkady",
  "Puthige",
  "Meenja",
  "Manjeshwar",
  "Paivalike",
  "Enmakaje",
  "Bellur",
  "Kumbadaje",
  "Muliyar",
  "Karadka",
  "Delampady",
  "Bedadka",
  "Kuttikol",
  "Chengala",
  "Chemnad",
  "Madhur",
  "Mogral Puthur",
  "Badiadka",
  "Kumbla",
  "Udma",
  "Ajanur",
  "Madikai",
  "Pallikere",
  "Pullur Periya",
  "Balal",
  "Kodom Belur",
  "Panathady",
  "Kallar",
  "East Eleri",
  "West Eleri",
  "Kinanoor - Karinthalam",
  "Cheruvathur",
  "Kayyur Cheemeni",
  "Pilicode",
  "Trikarpur",
  "Valiyaparamba",
  "Padne",
];


List<String> dataclass = ['APL', 'BPL','APL,BPL'];
List<String> dataclass2 = [
  "General",
  "OBC",
  "OEC",
  "SC",
  "ST",
];
List<String> salesmethod = [
  'direct'
  'localmarket'
  'cluster'
  'group'
  'wholesale'

];
List<String> familyincome = [
  "below2000",
  "20001_30000",
  "2001_5000",
  "5001_8333",
  "8334_20000",
  "above30000",
];

List<String> position = ['Member', 'familymember'];
List<String> house = ['Own', 'Rented'];
List<String> tf = ['Yes', 'No'];
List<String> enterpricetype = ['Individual', 'Group'];
List<String> loan = ['Applied', 'Sanctioned', 'Notapplied'];
List<String> condition = ['Yes Good', 'Yes Poor', 'No'];


final List options = [
  {'text': 'കോസ്റ്റൽ', 'value': 'Coastal'},
  {'text': 'ന്യൂനപക്ഷം', 'value': 'Minority'},
  {'text': 'അതി ദരിദ്രർ', 'value': 'Extreampoor'},
  {'text': 'ആശ്രയ', 'value': 'Asraya'},
  {'text': 'ശാരീരിക വെല്ലുവിളി ഉള്ളവർ', 'value': 'Physicallychallenged'},
  {'text': 'മാനസീക വെല്ലുവിളി /ബഡ്‌സ് ', 'value': 'MentalChallenge_Buds'},
  {'text': '60 വയസിനു മുകളിലുള്ളവർ', 'value': 'Thoseabove60yearsofage'},
  {'text': 'വിധവ', 'value': 'widow'},
  {'text': 'സ്ത്രീകൾ മാത്രമുള്ള കുടുംബം', 'value': 'femaleleaded'},
];


final List businesstype =  [
{ 'disply': 'പശു വളർത്തൽ', 'value': 'Cowbreeding' },
{ 'disply': 'ആട്  വളർത്തൽ ', 'value': 'Sheepfarming' },
{ 'disply': 'മുട്ട കോഴി വളർത്തൽ ', 'value': 'Breedingoflayinghens' },
{ 'disply': 'ഇറച്ചി കോഴി വളർത്തൽ ', 'value': 'Broilerfarming' },
{ 'disply': 'താറാവ് വളർത്തൽ ', 'value': 'Duckfarming' },
{ 'disply': 'പന്നി വളർത്തൽ ', 'value': 'Pigfarming' },
{ 'disply': 'മത്സ്യം വളർത്തൽ ', 'value': 'Fishfarming' },
{ 'disply': 'പോത്തു  വളർത്തൽ ', 'value': 'Cattlerearing' },
{ 'disply': 'എരുമ വളർത്തൽ ', 'value': 'Buffalorearing' },
{ 'disply': 'കാട വളർത്തൽ', 'value': 'Quailbreeding' },
{ 'disply': 'പെറ്റ്മൃഗങ്ങൾ വളർത്തൽ', 'value': 'Keepingpets' },
{ 'disply': 'പെറ്റ് ബേഡ്‌സ്  വളർത്തൽ   ', 'value': 'RaisingPetBirds' },
{ 'disply': 'തേനീച്ച വളർത്തൽ  ', 'value': 'Beekeeping' },
{ 'disply': 'വളം നിർമാണം  ', 'value': 'Fertilizermanufacturing' },
{ 'disply': 'കാലിത്തീറ്റ നിർമാണം ', 'value': 'Foddermanufacturing' },
{ 'disply': 'വാല്യൂ പ്രോഡക്റ്റ് നിർമാണം  ', 'value': 'valueproductcreation' },
{ 'disply': 'പുല്ല് കൃഷി', 'value': 'Cultivationofgrass' },
{ 'disply': 'പാൽ വിപണനം  ', 'value': 'Marketingofmilk' },
{ 'disply': 'ഇറച്ചി വിൽപന  ', 'value': 'Meatsales' },
{ 'disply': 'മാർക്കറ്റിങ് ', 'value': 'Marketing' },
{ 'disply': 'ഫാർമസി  ', 'value': 'Pharmacy' },
{ 'disply': 'പേരെൻറ് സ്റ്റോക്ക്', 'value': 'Parentstock' },
{ 'disply': ' എഗ്ഗർ നഴ്‌സറി  ', 'value': 'EggerNursery' },
{ 'disply': 'ഹാച്ചറി', 'value': 'Hatchery' },
{ 'disply': 'സംയോജിത കൃഷി', 'value': 'Integratedfarming' },
{ 'disply': 'മറ്റുള്ളവ ', 'value': 'Others' },
];

 List sourceofinvestment = [
  {'source': 'bankloan', 'value': 'bankloan'},
  {'source': 'Ng', 'value': 'Ng'},
  {'source': 'family', 'value': 'family'},
  {'source': 'friends', 'value': 'Asraya'},
  {'source': ' private finance', 'value': 'private finance'},
  {'source': 'other', 'value': 'other'},
];
